# Configurações globais para o Prometheus
global:
  # Frequência de coleta de métricas de todos os alvos
  scrape_interval: 5s

# Configurações específicas para a coleta de métricas
scrape_configs:
  # Configuração para o job chamado 'prometheus'
  - job_name: 'prometheus'
    # Configurações estáticas para este job
    static_configs:
      # Lista de alvos (targets) que o Prometheus deve coletar métricas
      - targets: ['localhost:9090']

  # Configuração para o job chamado 'simple_server_python'
  - job_name: 'simple_server_python'
    # Configurações estáticas para este job
    static_configs:
      # Lista de alvos (targets) que o Prometheus deve coletar métricas
      - targets: ['localhost:8091']

  # Configuração para o job chamado 'node-exporter'
  - job_name: 'node-exporter'
    # Configurações estáticas para este job
    static_configs:
      # Lista de alvos (targets) que o Prometheus deve coletar métricas do Node Exporter
      - targets: ['localhost:9100']

